=== ipmaia-internet-technologies-group-5/M1-Practical-Work/src/xml/projects/projects.xsd
<?xml version="1.0" encoding="utf-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.savetheforest.com" 
  xmlns:b="http://www.savetheforest.com" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <element name="projects">
    <complexType>
      <sequence>
        <element maxOccurs="unbounded" name="project">
          <complexType>
            <sequence>
              <element type="byte" name="id"/>
              <element type="string" name="title"/>
              <element type="string" name="description"/>
              <element type="string" name="image"/>
              <element type="int" name="goal"/>
              <element type="int" name="raised"/>
            </sequence>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>
</schema>

=== ipmaia-internet-technologies-group-5/M1-Practical-Work/src/xml/projects/projects.xml
<?xml version="1.0" encoding="UTF-8"?>

<projects xmlns="http://www.savetheforest.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.savetheforest.com
                             projects.xsd">
    <project>
        <id>0</id>
        <title>Title Test</title>
        <description>Description</description>
        <image>project1.png</image>
        <goal>50000</goal>
        <raised>30000</raised>
    </project>
    <project>
        <id>0</id>
        <title>Title Test</title>
        <description>Description</description>
        <image>project1.png</image>
        <goal>50000</goal>
        <raised>30000</raised>
    </project>
    <project>
        <id>0</id>
        <title>Title Test</title>
        <description>Description</description>
        <image>project1.png</image>
        <goal>50000</goal>
        <raised>30000</raised>
    </project>
    <project>
        <id>0</id>
        <title>Title Test</title>
        <description>Description</description>
        <image>project1.png</image>
        <goal>50000</goal>
        <raised>30000</raised>
    </project>
    <project>
        <id>0</id>
        <title>Title Test</title>
        <description>Description</description>
        <image>project1.png</image>
        <goal>50000</goal>
        <raised>30000</raised>
    </project>
    <project>
        <id>0</id>
        <title>Title Test</title>
        <description>Description</description>
        <image>project1.png</image>
        <goal>50000</goal>
        <raised>30000</raised>
    </project>
</projects>
